#!/usr/bin/python
"""Installs enrollment profiles with proper user account enrollment."""

# pylint: disable=E0611
import os
import subprocess

try:
    from SystemConfiguration import SCDynamicStoreCopyConsoleUser
except ImportError:
    print "This script requires the pyobjc bridge. Please use system python."
    exit(1)


def main():
    """Installs the enrollment profile at profilepath and enrolls the currently logged
    in user. For reference OS 16 == 10.12, 17 == 10.13. Note this does not get around
    UAMDM so on 10.13.2+ users will still need to click approve."""

    profilepath = '/var/tmp/switch-mdm/e.mobileconfig'
    username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]
    username = [username, ""][username in [u"loginwindow", None, u""]]
    print "Current username is %s" % username

    if float(os.uname()[2][0:2]) <= 16:
        cmd = ['/usr/bin/profiles', '-I', '-F', profilepath, '-Y', username]
    elif float(os.uname()[2][0:2]) == 17:
        cmd = ['/usr/bin/profiles', 'install', '-path', profilepath, '-enrolledUser', username]
    else:
        print "Error! Unsupported OS, too new."
        exit(1)

    result = subprocess.call(cmd)
    exit(result)

if __name__ == "__main__":
    main()
